# run `docker-compose up` to start both containers, ctrl+c to stop them
# run `docker-compose down -v` to remove containers and docker volumes
version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: sl-postgres
    environment:
      POSTGRES_USER: hacker_news_stories
      POSTGRES_DB: hacker_news_stories
      POSTGRES_PASSWORD: hacker_news_stories
    volumes:
      - sl-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      NODE_ENV: development
    restart: always
    ports:
      - "3000:3000"
volumes:
  sl-postgres:
    driver: local